### PR TITLE
Ignore static fields in copying

### PR DESCRIPTION
**Pull request by dallasgutauckis**

### CODE REVIEW

**Comment by dallasgutauckis** [comment]
@jkovacs I did this without testing it, because I don't know how to configure IntelliJ to run as a plugin when importing the project.

**Comment by dallasgutauckis** [comment]
cc/ @sddamico for a quick review as well

**Comment by dallasgutauckis** [comment]
@jkovacs Will this be something you can merge & deploy or should I maintain a fork?

**Comment by dallasgutauckis** [comment]
:+1:

**Comment by jkovacs** [comment]
Thanks @dallasgutauckis, good catch, and sorry for the delay, I had disabled email notifications :-(
I took the liberty of moving the static logic into its own method, as it is used in multiple places.
Will try to update the plugin repository with the newest version in the next couple of days. Thanks again!

**Pull request merged**
